In [2]:
import numpy as np
import tensorflow as tf
import pandas as pd
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers

In [3]:
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [4]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [5]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='object')

In [6]:
X = df[['soil_moisture', 'temperature_c', 'sunlight_hours']]
y = df['needs_water']

In [7]:
X_min = X.min()
X_max = X.max()
X_scaled = (X - X_min)/(X_max-X_min+ 1e-8)

In [8]:
X_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [9]:
X_train,X_test,y_train,y_test = train_test_split(
    X_scaled,y,test_size = 0.25,random_state = 42,stratify = y)

In [10]:
model = keras.Sequential([
    layers.Input(shape=(X_train.shape[1],)),
    layers.Dense(8,activation = 'relu'),
    layers.Dense(1,activation = 'sigmoid')
]
)

In [11]:
model.compile(optimizer = 'sgd',loss = 'binary_crossentropy',metrics = ['accuracy'])

In [14]:
history = model.fit(
    X_train.values,y_train.values,
    validation_data = (X_test.values,y_test.values),
    epochs = 100,batch_size = 4,verbose = 1
)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - accuracy: 0.9167 - loss: 0.6090 - val_accuracy: 1.0000 - val_loss: 0.6122
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.9167 - loss: 0.6086 - val_accuracy: 1.0000 - val_loss: 0.6116
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.9167 - loss: 0.6085 - val_accuracy: 1.0000 - val_loss: 0.6111
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.9167 - loss: 0.6078 - val_accuracy: 1.0000 - val_loss: 0.6105
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.9167 - loss: 0.6069 - val_accuracy: 1.0000 - val_loss: 0.6099
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.9167 - loss: 0.6057 - val_accuracy: 1.0000 - val_loss: 0.6094
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.9167 - loss: 0.6051 - val_accuracy: 1.0000 - val_loss: 0.6089
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.9167 - loss: 0.6050 - val_accuracy: 1.0000 - val_loss: 0.6083
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.9167 - loss: 0.6039 - val_accuracy: 1.0000 - val_loss: 0.6077
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.9167 - loss: 0.6039 - val_accuracy: 1.0000 - val_loss: 0.6071
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.9167 - loss: 0.6033 - val_accuracy: 1.0000 - val_loss: 0.6066
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.9167 - loss: 0.6025 - val_accuracy: 1.0000 - val_loss: 0.6060
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.9167 - loss: 0.6021 - val_accuracy: 1.0000 - val_loss: 0.6055
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.9167 - loss: 0.6009 - val_accuracy: 1.0000 - val_loss: 0.6049
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.9167 - loss: 0.6007 - val_accuracy: 1.0000 - val_loss: 0.6044
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step - accuracy: 0.9167 - loss: 0.6001 - val_accuracy: 1.0000 - val_loss: 0.6038
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step - accuracy: 0.9167 - loss: 0.5991 - val_accuracy: 1.0000 - val_loss: 0.6032
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.9167 - loss: 0.5985 - val_accuracy: 1.0000 - val_loss: 0.6027
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.9167 - loss: 0.5985 - val_accuracy: 1.0000 - val_loss: 0.6021
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.9167 - loss: 0.5982 - val_accuracy: 1.0000 - val_loss: 0.6015
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.9167 - loss: 0.5974 - val_accuracy: 1.0000 - val_loss: 0.6010
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.9167 - loss: 0.5965 - val_accuracy: 1.0000 - val_loss: 0.6004
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.9167 - loss: 0.5958 - val_accuracy: 1.0000 - val_loss: 0.5998
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.9167 - loss: 0.5949 - val_accuracy: 1.0000 - val_loss: 0.5993
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.9167 - loss: 0.5951 - val_accuracy: 1.0000 - val_loss: 0.5987
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.9167 - loss: 0.5953 - val_accuracy: 1.0000 - val_loss: 0.5982
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.9167 - loss: 0.5958 - val_accuracy: 1.0000 - val_loss: 0.5976
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.9167 - loss: 0.5941 - val_accuracy: 1.0000 - val_loss: 0.5970
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.9167 - loss: 0.5937 - val_accuracy: 1.0000 - val_loss: 0.5964
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.9167 - loss: 0.5918 - val_accuracy: 1.0000 - val_loss: 0.5959
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.9167 - loss: 0.5907 - val_accuracy: 1.0000 - val_loss: 0.5953
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.9167 - loss: 0.5905 - val_accuracy: 1.0000 - val_loss: 0.5947
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.9167 - loss: 0.5897 - val_accuracy: 1.0000 - val_loss: 0.5941
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.9167 - loss: 0.5887 - val_accuracy: 1.0000 - val_loss: 0.5935
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.9167 - loss: 0.5881 - val_accuracy: 1.0000 - val_loss: 0.5929
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.9167 - loss: 0.5882 - val_accuracy: 1.0000 - val_loss: 0.5923
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.9167 - loss: 0.5873 - val_accuracy: 1.0000 - val_loss: 0.5917
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.9167 - loss: 0.5875 - val_accuracy: 1.0000 - val_loss: 0.5912
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.9167 - loss: 0.5860 - val_accuracy: 1.0000 - val_loss: 0.5906
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.9167 - loss: 0.5856 - val_accuracy: 1.0000 - val_loss: 0.5900
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.9167 - loss: 0.5843 - val_accuracy: 1.0000 - val_loss: 0.5894
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.9167 - loss: 0.5838 - val_accuracy: 1.0000 - val_loss: 0.5888
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.9167 - loss: 0.5836 - val_accuracy: 1.0000 - val_loss: 0.5882
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.9167 - loss: 0.5850 - val_accuracy: 1.0000 - val_loss: 0.5876
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.9167 - loss: 0.5822 - val_accuracy: 1.0000 - val_loss: 0.5870
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.9167 - loss: 0.5819 - val_accuracy: 1.0000 - val_loss: 0.5864
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.9167 - loss: 0.5806 - val_accuracy: 1.0000 - val_loss: 0.5858
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.9167 - loss: 0.5805 - val_accuracy: 1.0000 - val_loss: 0.5851
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.9167 - loss: 0.5797 - val_accuracy: 1.0000 - val_loss: 0.5845
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.9167 - loss: 0.5793 - val_accuracy: 1.0000 - val_loss: 0.5839
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.9167 - loss: 0.5786 - val_accuracy: 1.0000 - val_loss: 0.5833
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.9167 - loss: 0.5794 - val_accuracy: 1.0000 - val_loss: 0.5827
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.9167 - loss: 0.5768 - val_accuracy: 1.0000 - val_loss: 0.5821
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.9167 - loss: 0.5767 - val_accuracy: 1.0000 - val_loss: 0.5815
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.9167 - loss: 0.5763 - val_accuracy: 1.0000 - val_loss: 0.5809
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.9167 - loss: 0.5756 - val_accuracy: 1.0000 - val_loss: 0.5803
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.9167 - loss: 0.5741 - val_accuracy: 1.0000 - val_loss: 0.5796
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.9167 - loss: 0.5740 - val_accuracy: 1.0000 - val_loss: 0.5790
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.9167 - loss: 0.5750 - val_accuracy: 1.0000 - val_loss: 0.5784
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.9167 - loss: 0.5722 - val_accuracy: 1.0000 - val_loss: 0.5777
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.9167 - loss: 0.5722 - val_accuracy: 1.0000 - val_loss: 0.5771
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.9167 - loss: 0.5717 - val_accuracy: 1.0000 - val_loss: 0.5764
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.9167 - loss: 0.5726 - val_accuracy: 1.0000 - val_loss: 0.5758
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.9167 - loss: 0.5702 - val_accuracy: 1.0000 - val_loss: 0.5752
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.9167 - loss: 0.5689 - val_accuracy: 1.0000 - val_loss: 0.5745
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.9167 - loss: 0.5682 - val_accuracy: 1.0000 - val_loss: 0.5739
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.9167 - loss: 0.5677 - val_accuracy: 1.0000 - val_loss: 0.5733
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.9167 - loss: 0.5669 - val_accuracy: 1.0000 - val_loss: 0.5726
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.9167 - loss: 0.5688 - val_accuracy: 1.0000 - val_loss: 0.5720
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.9167 - loss: 0.5657 - val_accuracy: 1.0000 - val_loss: 0.5714
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.9167 - loss: 0.5657 - val_accuracy: 1.0000 - val_loss: 0.5707
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.9167 - loss: 0.5660 - val_accuracy: 1.0000 - val_loss: 0.5700
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.9167 - loss: 0.5646 - val_accuracy: 1.0000 - val_loss: 0.5694
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.9167 - loss: 0.5630 - val_accuracy: 1.0000 - val_loss: 0.5688
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.9167 - loss: 0.5628 - val_accuracy: 1.0000 - val_loss: 0.5681
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.9167 - loss: 0.5637 - val_accuracy: 1.0000 - val_loss: 0.5675
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.9167 - loss: 0.5617 - val_accuracy: 1.0000 - val_loss: 0.5668
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.9167 - loss: 0.5610 - val_accuracy: 1.0000 - val_loss: 0.5662
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.9167 - loss: 0.5603 - val_accuracy: 1.0000 - val_loss: 0.5656
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.9167 - loss: 0.5591 - val_accuracy: 1.0000 - val_loss: 0.5650
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.9167 - loss: 0.5594 - val_accuracy: 1.0000 - val_loss: 0.5644
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.9167 - loss: 0.5588 - val_accuracy: 1.0000 - val_loss: 0.5638
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.9167 - loss: 0.5576 - val_accuracy: 1.0000 - val_loss: 0.5632
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.9167 - loss: 0.5568 - val_accuracy: 1.0000 - val_loss: 0.5625
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.9167 - loss: 0.5565 - val_accuracy: 1.0000 - val_loss: 0.5619
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.9167 - loss: 0.5560 - val_accuracy: 1.0000 - val_loss: 0.5613
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.9167 - loss: 0.5547 - val_accuracy: 1.0000 - val_loss: 0.5607
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.9167 - loss: 0.5547 - val_accuracy: 1.0000 - val_loss: 0.5601
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.9167 - loss: 0.5552 - val_accuracy: 1.0000 - val_loss: 0.5595
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.9167 - loss: 0.5527 - val_accuracy: 1.0000 - val_loss: 0.5588
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.9167 - loss: 0.5542 - val_accuracy: 1.0000 - val_loss: 0.5582
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.9167 - loss: 0.5518 - val_accuracy: 1.0000 - val_loss: 0.5576
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.9167 - loss: 0.5527 - val_accuracy: 1.0000 - val_loss: 0.5570
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.9167 - loss: 0.5501 - val_accuracy: 1.0000 - val_loss: 0.5563
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - accuracy: 0.9167 - loss: 0.5502 - val_accuracy: 1.0000 - val_loss: 0.5557
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.9167 - loss: 0.5488 - val_accuracy: 1.0000 - val_loss: 0.5550
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.9167 - loss: 0.5490 - val_accuracy: 1.0000 - val_loss: 0.5544
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.9167 - loss: 0.5481 - val_accuracy: 1.0000 - val_loss: 0.5538
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.9167 - loss: 0.5468 - val_accuracy: 1.0000 - val_loss: 0.5531
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.9167 - loss: 0.5491 - val_accuracy: 1.0000 - val_loss: 0.5524